// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTI41NtLXQZHh4zn-ceCoSKWk-UdaOEnM',
    appId: '1:910916170426:web:8bbf7bd2ef79c2fd1c8883',
    messagingSenderId: '910916170426',
    projectId: 'mynotes-sbf',
    authDomain: 'mynotes-sbf.firebaseapp.com',
    storageBucket: 'mynotes-sbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE33JZTY5QSETdqmal14Bk_XiLWJIsF1I',
    appId: '1:910916170426:android:6a08fcf1e177e14b1c8883',
    messagingSenderId: '910916170426',
    projectId: 'mynotes-sbf',
    storageBucket: 'mynotes-sbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB22oOA45UzGHNg8cOA5V_5059vkN34FNs',
    appId: '1:910916170426:ios:3563dfc147298dc11c8883',
    messagingSenderId: '910916170426',
    projectId: 'mynotes-sbf',
    storageBucket: 'mynotes-sbf.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB22oOA45UzGHNg8cOA5V_5059vkN34FNs',
    appId: '1:910916170426:ios:0d568977f3a55dd51c8883',
    messagingSenderId: '910916170426',
    projectId: 'mynotes-sbf',
    storageBucket: 'mynotes-sbf.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
